version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
    - dependabot
    ignore:
      - dependency-name: localstack/localstack
        versions:
          - ">= 0.13"