version: '3.8'

services:
  aws:
    image: localstack/localstack:0.12.20@sha256:ae2c8cbf90ec8dace5d34ff5690b049f030021a0c1a2f8e49bcb8cd6986fae52
    environment:
      SERVICES: iam, ec2, sqs, s3, sts, kms, sns, ssm, cloudwatch
      EDGE_PORT: "45678"
      EXTERNAL_HOSTNAME: localhost
      DEFAULT_REGION: eu-west-2
      TEST_AWS_ACCOUNT_ID: 123456789012
      DEBUG: "1"
      KMS_PROVIDER: local-kms
    extra_hosts:
      - "notify.internal:host-gateway"
      - "subscriber.internal:host-gateway"
    networks:
      - di-authentication-api-net
    ports:
      - 45678:45678

  redis:
    image: redis:6.0.5-alpine
    healthcheck:
      test: '[[ $$(redis-cli ping 2> /dev/null) == "PONG" ]] || exit 1'
      interval: 5s
      timeout: 1m
    ports:
      - 6379:6379
    networks:
      - di-authentication-api-net

  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ."
    working_dir: /home/dynamodblocal
    image: amazon/dynamodb-local:latest
    healthcheck:
      test: curl http://localhost:8000
      interval: 5s
      timeout: 1m
    ports:
      - 8000:8000
    networks:
      - di-authentication-api-net

networks:
  di-authentication-api-net:
