name: Deploy Delivery Receipts to Dev

env:
  # DevPlatform recommend that the below vars are added to GitHub secrets
  GHA_ROLE: arn:aws:iam::761723964695:role/dev-auth-deploy-pipeline-GitHubActionsRole-1IIFWOJDUI5B9
  DESTINATION_BUCKET: di-auth-lambda-signed-20220215170204376200000002
  ARTIFACT_BUCKET: dev-auth-deploy-pipeline-githubartifactsourcebuck-1nh86k5wimx9n

on:
  push:
    branches:
      - main
    paths:
      - "delivery-receipts"
  workflow_run:
    workflows: ["Build modules"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.GHA_ROLE }}
          aws-region: eu-west-2
      
      - name: Download and copy Delivery Receipts signed lambda zip
        working-directory: ci/terraform/delivery-receipts
        run: |
          aws s3 cp s3://${{ env.DESTINATION_BUCKET }} ./artifacts \
            --recursive --exclude "*" \
            --include "signed-delivery-receipts-api-${{ github.sha }}-*"
          mv artifacts/signed-delivery-receipts-api-*.zip artifacts/delivery-receipts-api.zip

      - name: Upload Delivery Receipts Terraform files
        working-directory: ci/terraform
        run: |
          zip -r delivery-receipts.zip .
          S3_RESPONSE=`aws s3api put-object \
            --bucket $ARTIFACT_BUCKET \
            --key delivery-receipts.zip \
            --body delivery-receipts.zip`
          VERSION=`echo $S3_RESPONSE | jq .VersionId -r`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
 