name: Deploy Utils to Dev

env:
  # DevPlatform recommend that the below vars are added to GitHub secrets
  DEPLOYER_ROLE: arn:aws:iam::761723964695:role/deployer-role-pipeline-dev
  DESTINATION_BUCKET: di-auth-lambda-signed-20220215170204376200000002

on:
  push:
    branches:
      - main
    paths:
      - "utils"
  workflow_run:
    workflows: ["Build modules"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.DEPLOYER_ROLE }}
          aws-region: eu-west-2
      
      - name: Download and copy Audit Processors signed lambda zip
        working-directory: ci/terraform/utils
        run: |
          aws s3 cp s3://dev-platform-destination-test/ ./artifacts 
          --recursive --exclude "*" 
          --include "signed-utils-${{ github.sha }}-*"
          mv artifacts/signed-utils-*.zip artifacts/utils.zip

      - name: Upload Utils Terraform files
        working-directory: ci/terraform
        run: |
          zip -r template.zip .
          S3_RESPONSE=`aws s3api put-object \
            --bucket dev-auth-deploy-pipeline-githubartifactsourcebuck-1nh86k5wimx9n \
            --key template.zip \
            --body template.zip`
          VERSION=`echo $S3_RESPONSE | jq .VersionId -r`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
 