name: Deploy Utils

env:
  GHA_ROLE: arn:aws:iam::761723964695:role/build-auth-deploy-pipeline-GitHubActionsRole-160U5ADTRKQ2O
  DESTINATION_BUCKET: di-auth-lambda-signed-20220215170204376200000002
  ARTIFACT_BUCKET: build-auth-deploy-pipeli-githubartifactsourcebuck-1o4hcrnik6ayv

on:
  workflow_run:
    workflows: ["Build modules"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.GHA_ROLE }}
          aws-region: eu-west-2

      - name: Download and copy Utils signed lambda zip
        working-directory: ci/terraform/utils
        run: |
          aws s3 cp s3://${{ env.DESTINATION_BUCKET }} ./artifacts \
            --recursive --exclude "*" \
            --include "signed-utils-${{ github.sha }}-*"
          mv artifacts/signed-utils-*.zip artifacts/utils.zip

      - name: Upload Utils Terraform files
        uses: ./.github/actions/upload-terraform
        with:
          artifact-bucket: ${{ env.ARTIFACT_BUCKET }}
          artifact-key: utils.zip
