name: Deploy Account Management

env:
  GHA_ROLE: arn:aws:iam::761723964695:role/build-auth-deploy-pipeline-GitHubActionsRole-160U5ADTRKQ2O
  DESTINATION_BUCKET: di-auth-lambda-signed-20220215170204376200000002
  ARTIFACT_BUCKET: build-auth-deploy-pipeli-githubartifactsourcebuck-1o4hcrnik6ayv

on:
  push:
    branches:
      - main
    paths:
      - "account-management"
  workflow_run:
    workflows: ["Build modules"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.GHA_ROLE }}
          aws-region: eu-west-2
      
      - name: Download and copy Account Management signed lambda zip
        working-directory: ci/terraform/account-management
        run: |
          aws s3 cp s3://${{ env.DESTINATION_BUCKET }} ./artifacts \
            --recursive --exclude "*" \
            --include "signed-account-management-api-${{ github.sha }}-*"
          mv artifacts/signed-account-management-*.zip artifacts/account-management-api.zip

      - name: Upload Account Management Terraform files
        working-directory: ci/terraform
        run: |
          zip -r account-management.zip .
          S3_RESPONSE=`aws s3api put-object \
            --bucket $ARTIFACT_BUCKET \
            --key account-management.zip \
            --body account-management.zip`
          VERSION=`echo $S3_RESPONSE | jq .VersionId -r`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
 